import { ColorModel } from "../database/color.model";
import { connect, disconnect } from "../database"
(async () => {
  connect();
  const colors = [
    { _id: 1, colorName: "Lavender", colorHue: "#E6E6FA", colorGroup: "Purple"},
    { _id: 2, colorName: "Thistle", colorHue: "#D8BFD8", colorGroup: "Purple"},
    { _id: 3, colorName: "Orchid", colorHue: "#DA70D6", colorGroup: "Purple"},
    { _id: 4, colorName: "Magenta", colorHue: "#FF00FF", colorGroup: "Purple"},
    { _id: 5, colorName: "Medium Orchid", colorHue: "#BA55D3", colorGroup: "Purple"},
    { _id: 6, colorName: "Dark Orchid", colorHue: "#9932CC", colorGroup: "Purple"},
    { _id: 7, colorName: "Dark Violet", colorHue: "#9400D3", colorGroup: "Purple"},
    { _id: 8, colorName: "Blue Violet", colorHue: "#8A2BE2", colorGroup: "Purple"},
    { _id: 9, colorName: "Dark Magenta", colorHue: "#8B008B", colorGroup: "Purple"},
    { _id: 10, colorName: "Purple", colorHue: "#800080", colorGroup: "Purple"},
    { _id: 11, colorName: "Medium Purple", colorHue: "#9370DB", colorGroup: "Purple"},
    { _id: 12, colorName: "Medium Slate Blue", colorHue: "#7B68EE", colorGroup: "Purple"},
    { _id: 13, colorName: "Rebecca Purple", colorHue: "#663399", colorGroup: "Purple"},
    { _id: 14, colorName: "Indigo", colorHue: "#4B0082", colorGroup: "Purple"},
    { _id: 15, colorName: "Light Salmon", colorHue: "#FFA07A", colorGroup: "Red"},
    { _id: 16, colorName: "Salmon", colorHue: "#FA8072", colorGroup: "Red"},
    { _id: 17, colorName: "Dark Salmon", colorHue: "#E9967A", colorGroup: "Red"},
    { _id: 18, colorName: "Light Coral", colorHue: "#F08080", colorGroup: "Red"},
    { _id: 19, colorName: "Indian Red", colorHue: "#CD5C5C", colorGroup: "Red"},
    { _id: 20, colorName: "Crimson", colorHue: "#DC143C", colorGroup: "Red"},
    { _id: 21, colorName: "Red", colorHue: "#FF0000", colorGroup: "Red"},
    { _id: 22, colorName: "Fire Brick", colorHue: "#B22222", colorGroup: "Red"},
    { _id: 23, colorName: "Dark Red", colorHue: "#8B0000", colorGroup: "Red"},
    { _id: 24, colorName: "Orange", colorHue: "#FFA500", colorGroup: "Orange"},
    { _id: 25, colorName: "Dark Orange", colorHue: "#FF8C00", colorGroup: "Orange"},
    { _id: 26, colorName: "Coral", colorHue: "#FF7F50", colorGroup: "Orange"},
    { _id: 27, colorName: "Tomato", colorHue: "#FF6347", colorGroup: "Orange"},
    { _id: 28, colorName: "Orange Red", colorHue: "#FF4500", colorGroup: "Orange"},
    { _id: 29, colorName: "Gold", colorHue: "#FFD700", colorGroup: "Yellow"},
    { _id: 30, colorName: "Yellow", colorHue: "#FFFF00", colorGroup: "Yellow"},
    { _id: 31, colorName: "Light Yellow", colorHue: "#FFFFE0", colorGroup: "Yellow"},
    { _id: 32, colorName: "Lemon Chiffon", colorHue: "#FFFACD", colorGroup: "Yellow"},
    { _id: 33, colorName: "Light Golden Rod Yellow", colorHue: "#FAFAD2", colorGroup: "Yellow"},
    { _id: 34, colorName: "Papaya Whip", colorHue: "#FFEFD5", colorGroup: "Yellow"},
    { _id: 35, colorName: "Moccasin", colorHue: "#FFE4B5", colorGroup: "Yellow"},
    { _id: 36, colorName: "Peach Puff", colorHue: "#FFDAB9", colorGroup: "Yellow"},
    { _id: 37, colorName: "Pale Golden Rod", colorHue: "#EEE8AA", colorGroup: "Yellow"},
    { _id: 38, colorName: "Khaki", colorHue: "#F0E68C", colorGroup: "Yellow"},
    { _id: 39, colorName: "Green Yellow", colorHue: "#ADFF2F", colorGroup: "Green"},
    { _id: 40, colorName: "Chartruse", colorHue: "#7FFF00", colorGroup: "Green"},
    { _id: 41, colorName: "Lawn Green", colorHue: "#7CFC00", colorGroup: "Green"},
    { _id: 42, colorName: "Lime", colorHue: "#00FF00", colorGroup: "Green"},
    { _id: 43, colorName: "Lime Green", colorHue: "#32CD32", colorGroup: "Green"},
    { _id: 44, colorName: "Pale Green", colorHue: "#98FB98", colorGroup: "Green"},
    { _id: 45, colorName: "Light Green", colorHue: "#90EE90", colorGroup: "Green"},
    { _id: 46, colorName: "Spring Green", colorHue: "#00FF7F", colorGroup: "Green"},
    { _id: 47, colorName: "Medium Sea Green", colorHue: "#3CB371", colorGroup: "Green"},
    { _id: 48, colorName: "Sea Green", colorHue: "#2E8B57", colorGroup: "Green"},
    { _id: 49, colorName: "Forest Green", colorHue: "#228B22", colorGroup: "Green"},
    { _id: 50, colorName: "Green", colorHue: "#008000", colorGroup: "Green"},
    { _id: 51, colorName: "Dark Green", colorHue: "#006400", colorGroup: "Green"},
    { _id: 52, colorName: "Yellow Green", colorHue: "#9ACD32", colorGroup: "Green"},
    { _id: 53, colorName: "Olive Drab", colorHue: "#6B8E23", colorGroup: "Green"},
    { _id: 54, colorName: "Dark Olive Green", colorHue: "#556B2F", colorGroup: "Green"},
    { _id: 55, colorName: "Dark Sea Green", colorHue: "#8FBC8F", colorGroup: "Green"},
    { _id: 56, colorName: "Light Sea Green", colorHue: "#20B2AA", colorGroup: "Green"},
    { _id: 57, colorName: "Dark Cyan", colorHue: "#008B8B", colorGroup: "Green"},
    { _id: 58, colorName: "Teal", colorHue: "#008080", colorGroup: "Green"},
    { _id: 59, colorName: "Cadet Blue", colorHue: "#5F9EA0", colorGroup: "Blue"},
    { _id: 60, colorName: "Blue", colorHue: "#0000FF", colorGroup: "Blue"},
    { _id: 61, colorName: "Steel Blue", colorHue: "#4682B4", colorGroup: "Blue"},
    { _id: 62, colorName: "Light Steel Blue", colorHue: "#B0C4DE", colorGroup: "Blue"},
    { _id: 63, colorName: "Light Blue", colorHue: "#ADD8E6", colorGroup: "Blue"},
    { _id: 64, colorName: "Powder Blue", colorHue: "#B0E0E6", colorGroup: "Blue"},
    { _id: 65, colorName: "Light Sky Blue", colorHue: "#87CEFA", colorGroup: "Blue"},
    { _id: 66, colorName: "Sky Blue", colorHue: "#87CEEB", colorGroup: "Blue"},
    { _id: 67, colorName: "Cornflower Blue", colorHue: "#6495ED", colorGroup: "Blue"},
    { _id: 68, colorName: "Deep Sky Blue", colorHue: "#00BFFF", colorGroup: "Blue"},
    { _id: 69, colorName: "Dodger Blue", colorHue: "#1E90FF", colorGroup: "Blue"},
    { _id: 70, colorName: "Royal Blue", colorHue: "#4169E1", colorGroup: "Blue"},
    { _id: 71, colorName: "Medium Blue", colorHue: "#0000CD", colorGroup: "Blue"},
    { _id: 72, colorName: "Dark Blue", colorHue: "#00008B", colorGroup: "Blue"},
    { _id: 73, colorName: "Navy", colorHue: "#000080", colorGroup: "Blue"},
    { _id: 74, colorName: "Midnight Blue", colorHue: "#191970", colorGroup: "Blue"},
    { _id: 75, colorName: "Cornsilk", colorHue: "#FFF8DC", colorGroup: "Brown"},
    { _id: 76, colorName: "Blanched Almond", colorHue: "#FFEBCD", colorGroup: "Brown"},
    { _id: 77, colorName: "Bisque", colorHue: "#FFE4C4", colorGroup: "Brown"},
    { _id: 78, colorName: "Navajo White", colorHue: "#FFDEAD", colorGroup: "Brown"},
    { _id: 79, colorName: "Wheat", colorHue: "#F5DEB3", colorGroup: "Brown"},
    { _id: 80, colorName: "Burly Wood", colorHue: "#DEB887", colorGroup: "Brown"},
    { _id: 81, colorName: "Tan", colorHue: "#D2B48C", colorGroup: "Brown"},
    { _id: 82, colorName: "Rosy Brown", colorHue: "#BC8F8F", colorGroup: "Brown"},
    { _id: 83, colorName: "Golden Rod", colorHue: "#DAA520", colorGroup: "Brown"},
    { _id: 84, colorName: "Sandy Brown", colorHue: "#F4A460", colorGroup: "Brown"},
    { _id: 85, colorName: "Dark Golden Rod", colorHue: "#B8860B", colorGroup: "Brown"},
    { _id: 86, colorName: "Peru", colorHue: "#CD853F", colorGroup: "Brown"},
    { _id: 87, colorName: "Chocolate", colorHue: "#D2691E", colorGroup: "Brown"},
    { _id: 88, colorName: "Olive", colorHue: "#808000", colorGroup: "Brown"},
    { _id: 89, colorName: "Saddle Brown", colorHue: "#8B4513", colorGroup: "Brown"},
    { _id: 90, colorName: "Sienna", colorHue: "#A0522D", colorGroup: "Brown"},
    { _id: 91, colorName: "Brown", colorHue: "#A52A2A", colorGroup: "Brown"},
    { _id: 92, colorName: "Maroon", colorHue: "#800000", colorGroup: "Brown"},
    { _id: 93, colorName: "Gainsboro", colorHue: "#DCDCDC", colorGroup: "Grey"},
    { _id: 94, colorName: "Light Grey", colorHue: "#D3D3D3", colorGroup: "Grey"},
    { _id: 95, colorName: "Silver", colorHue: "#C0C0C0", colorGroup: "Grey"},
    { _id: 96, colorName: "Dark Grey", colorHue: "#A9A9A9", colorGroup: "Grey"},
    { _id: 97, colorName: "Dim Grey", colorHue: "#696969", colorGroup: "Grey"},
    { _id: 98, colorName: "Grey", colorHue: "#808080", colorGroup: "Grey"},
    { _id: 99, colorName: "Light Slate Grey", colorHue: "#778899", colorGroup: "Grey"},
    { _id: 100, colorName: "Slate Grey", colorHue: "#708090", colorGroup: "Grey"},
    { _id: 101, colorName: "Black", colorHue: "#000000", colorGroup: "Grey"},

    
    
  ];
  try {
    for (const color of colors) {
      await ColorModel.create(color);
      console.log(`Created color ${color.colorName} ${color.colorHue}`);
    }
    disconnect();
  } catch (e) {
    console.error(e);
  }
})();